-- Generated by scripts/build-registry-catalog.mjs from the application repository.
-- A bundled id ships inside Shun, so the registry refuses to publish under it.
DELETE FROM reserved_ids;
INSERT OR REPLACE INTO reserved_ids (id, owner, note) VALUES ('browser-preview', 'first-party', 'bundled with Shun');
INSERT OR REPLACE INTO reserved_ids (id, owner, note) VALUES ('browser-use', 'first-party', 'a first-party connector shipped with Shun');
INSERT OR REPLACE INTO reserved_ids (id, owner, note) VALUES ('cloudflare', 'first-party', 'a first-party connector shipped with Shun');
INSERT OR REPLACE INTO reserved_ids (id, owner, note) VALUES ('figma', 'first-party', 'a first-party connector shipped with Shun');
INSERT OR REPLACE INTO reserved_ids (id, owner, note) VALUES ('file-manager', 'first-party', 'bundled with Shun');
INSERT OR REPLACE INTO reserved_ids (id, owner, note) VALUES ('git-workbench', 'first-party', 'bundled with Shun');
INSERT OR REPLACE INTO reserved_ids (id, owner, note) VALUES ('github', 'first-party', 'a first-party connector shipped with Shun');
INSERT OR REPLACE INTO reserved_ids (id, owner, note) VALUES ('gmail', 'first-party', 'a first-party connector shipped with Shun');
INSERT OR REPLACE INTO reserved_ids (id, owner, note) VALUES ('godot', 'first-party', 'a first-party connector shipped with Shun');
INSERT OR REPLACE INTO reserved_ids (id, owner, note) VALUES ('ios-simulator', 'first-party', 'a first-party connector shipped with Shun');
INSERT OR REPLACE INTO reserved_ids (id, owner, note) VALUES ('render', 'first-party', 'a first-party connector shipped with Shun');
INSERT OR REPLACE INTO reserved_ids (id, owner, note) VALUES ('sites', 'first-party', 'bundled with Shun');
INSERT OR REPLACE INTO reserved_ids (id, owner, note) VALUES ('terminal', 'first-party', 'bundled with Shun');
