import { render } from 'preact'
import { App } from './app'
import '@fontsource-variable/newsreader'
import 'katex/dist/katex.min.css'
import './style.css'
import './status.css'
import './motion.css'
import './polish.css'
import './functional.css'
import './repository-status.css'
import './settings-page.css'
import './type.css'
import './composer.css'
import './layout-fix.css'
import './semantic.css'
import './interaction-fix.css'
import './capabilities.css'
import './composer-state.css'
import './background-processes.css'
import './tool-fix.css'
import './agent-feed.css'
import './trace-polish.css'
import './link-polish.css'
import './change-review.css'
import './task-tree.css'
import './task-refine.css'
import './task-lifecycle.css'
import './project-picker.css'
import './message-layout.css'
import './math.css'
import './mermaid.css'
import './final-refine.css'
import './plugin-hub.css'
import './app-update.css'
import './attachments.css'
import './loading.css'

render(<App />, document.getElementById('app')!)
